# Generated by Django 5.0.4 on 2024-05-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shippingaddress_number_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
